### ISSUE TITLE
Peer Review #2

### ISSUE THREAD

**Issue by koyunkyung** [JuliaJLee/Toronto_Paramedic_Services#2]
**Opening statement summary**

This paper focuses on discovering how the driving factors of EMS(emergency medical services) demand are distributed, through investigation of time-series frequency fluctuations. Line plot of the total number of emergency calls and respective line plots of various EMS demand sources over the date period of year 2017 to 2022 were used. Based on the analysis results, the paper intends to propose a resource redistribution plan to solve the supply shortage of Toronto paramedic services.

**Strong positive points**

The problem situation and research motivation were clearly expressed so that the necessity of the study could be easily persuaded.

**Critical improvements needed**

The paper is likely to become more reliable and accurate if the ‘Data’ part includes not only parts of the raw data (as it is in the current paper draft), but also graphs/tables of summary statistics of the analysis data. It might get even better if the discussion of the reason why ‘different incident types’ variable was selected for analysis and others were not.

For the credibility of claims in the paper, it is highly recommended to correct typos like ‘EMS Demand From 2017 to 2022)’ (the title label of Figure 1) and correct the codes to prevent error messages from appearing on the paper (warning message at the bottom of page 3).

It is expected to be a more useful and fruitful thesis with the ‘Discussion’ part supplemented. Enriching the sub-sections of what we learn about the world with detailed real-time instances might be a good idea. Furthermore, mentioning some of the weaknesses of what was done, regarding things such as the data used, might be recommended.

**Suggestions for improvement:**

Please consider adding/changing/removing:

1. ‘Title’ in a more descriptive and persuasive manner
: Though the current title of the paper also looks fine, it feels like main title doesn’t fully comprehend the specificity and necessity of the subject, which was actually covered in the paper. 

2. Figure 3 in the ‘Results’ part with colors that are difficult to distinguish at a glance
: The yellow color indicating ‘Emergency Transfers’, which looks like a vital part the readers should recognize in the context, is not clearly visible. It is suggested to change it to a color that is more noticeable and contrasting with white.

3. Arrangement of Result description sentences and graphs
: In the reader’s perspective, it would be more convenient for the result descriptions to be near to the related graphs. Thus, it is suggested to put Figure 1 right below the paragraphs of 3.1, Figure 2 and 3 right below the paragraphs of 3.2, and so on. 

**Evaluation:** 

- R is cited : 1/1
- LLM usage is documented : 0/1
- Title : 1/2
- Author, date, and repo : 2/2
- Abstract : 2/4
- Introduction : 3/4
- Data : 4/10
- Measurement : 3/4
- Cross-references : 2/2
- Prose : 4/6
- Graphs/tables/etc : 2/4
- Referencing : 4/4
- Commits : 2/2
- Sketches : 2/2
- Simulation : 3/4
- Tests : 3/4
- Reproducibility : 3/4
- Code style : 0/1
- General excellence : 1/3

**Estimated mark:**

42 out of 64.

**Reason:**

The overall structure of the paper was fine and the story to be conveyed was well expressed. It could be a complete academic paper with modification of minor details and supplementation of the contents.

**Comment by jjlee-lee** [comment]
Thank you for your feedback! As per your suggestions, I included tables of the analysis data, corrected typos, and organized the sections of my paper to ensure better flow.
