### ISSUE TITLE
peer review# Zeyi Cai

### ISSUE THREAD

**Issue by ZeyiCai** [JuliaJLee/Toronto_Paramedic_Services#4]
Opening statement summary

Your article is through the study of nursing staff service events.

Data (2017-2022) to determine the key drivers of emergency medical service (EMS) demand.

Finally, I expounded my views and believed that seeking better management strategies can improve the overall efficiency of nursing services. The theme is very clear!

Strong positive points

Your summary, introduction and data analysis are particularly detailed! The overall structure is particularly complete and very readable!

Critical improvements needed

Suggestions for improvement:

Your problem is that you can put a brief introduction under each chart in the chart analysis part, and placing the data analysis part under each corresponding chart will make readers more intuitive to understand your results.
Please consider adding/changing/removing:

Evaluation: 

Overall, I really enjoy the paper.

Estimated mark:

[90] out of 100.

**Comment by jjlee-lee** [comment]
Thank you for your feedback! As per your suggestions, I organized my results section so that it is easier for readers to understand which explanation corresponds to each figure provided.
