### ISSUE TITLE
Example and a small tweak

### ISSUE THREAD

**Issue by RohanAlexander** [JuliaJLee/Toronto_Paramedic_Services#5]
May I use this as an example please?

If so, can you please make this small change to your bibtex file and then recompile the PDF:

Old: title = {Welcome to the tidyverse.},
New: title = {Welcome to the tidyverse},

Old: title = {Dplyr: A Grammar of Data Manipulation},
New: title = {{dplyr: A Grammar of Data Manipulation}},

Old: title = {opendatatoronto: Access the City of Toronto Open Data Portal},
New: title = {{opendatatoronto: Access the City of Toronto Open Data Portal}},

Old: title = {ggplot2: Elegant Graphics for Data Analysis},
New: title = {{ggplot2: Elegant Graphics for Data Analysis}},

Old: title = {maps: Draw Geographical Maps},
New: title = {{maps: Draw Geographical Maps}},

Old: author = {{Esri,}},
New: author = {{Esri}},

**Comment by jjlee-lee** [comment]
Yes! I have pushed the changes made to my bibex file and a new pdf to GitHub. Thank you!
